### ISSUE TITLE
rails 3.1 warnings

### ISSUE THREAD

**Issue by dmitry-a-l** [caelum/hypertemplate#6]
Under rails 3.1.3 I have

DEPRECATION WARNING: Inheriting from ActionView::Template::Handler is deprecated
DEPRECATION WARNING: Including Compilable in your template handler is deprecated

This warnings produced by lib/hypertemplate/hook/rails.rb

**Comment by divoxx** [comment]
This actually breaks in newer versions of Rails, which is a huge problem since it block Rails from being upgraded and giving the latest rails security issues I'd say upgrading is not something you'd choose not to do.

@guilhermesilveira are you guys not maintaining this anymore?

**Comment by guilhermesilveira** [comment]
Hi Rodrigo

I canhelp out if someone can help me finding the new way to implement a nrw
template handler. I am currently out of sao paulo so I am glad to push any
suggestions in

Cheers
On Jun 13, 2012 8:28 PM, "Rodrigo Kochenburger" <
reply@reply.github.com>
wrote:

**Comment by brunoadacosta** [comment]
@guilhermesilveira 
this may be a possible solution

https://gist.github.com/3049471

**Comment by brunoadacosta** [comment]
fixed in 1.2.2

c935312
